#!/bin/bash

# Script to verify what API URL was baked into the Netlify build
# This helps confirm if the environment variable was set correctly

echo "Checking what API URL is in the deployed build..."
echo ""
echo "Method 1: Check the built JavaScript file"
echo "----------------------------------------"
echo "1. Go to: https://www.clearways.ai"
echo "2. Open browser developer tools (F12)"
echo "3. Go to Network tab"
echo "4. Refresh the page"
echo "5. Find the main JavaScript file (e.g., index-CMf6HEZO.js or similar)"
echo "6. Right-click → Open in new tab"
echo "7. Search for 'clearways-ai-backend' or 'api.clearways.ai'"
echo ""
echo "You should see:"
echo "  ✅ 'api.clearways.ai' = Environment variable was set correctly"
echo "  ❌ 'clearways-ai-backend-env.eba-skxjjmed' = Environment variable was NOT updated"
echo ""
echo ""
echo "Method 2: Check Netlify Environment Variables"
echo "---------------------------------------------"
echo "1. Go to: https://app.netlify.com"
echo "2. Select your site"
echo "3. Site settings → Environment variables"
echo "4. Verify VITE_API_URL = 'https://api.clearways.ai/api'"
echo ""
echo ""
echo "Method 3: Check Build Logs for Environment Variables"
echo "-----------------------------------------------------"
echo "1. Go to Netlify Dashboard → Deploys tab"
echo "2. Click on the latest deployment"
echo "3. Look for 'Environment variables' section in the build logs"
echo "4. Verify VITE_API_URL is listed with the correct value"
echo ""
echo ""
echo "If the URL is still wrong:"
echo "1. Update VITE_API_URL in Netlify to: https://api.clearways.ai/api"
echo "2. Trigger a NEW deployment (Deploys → Trigger deploy)"
echo "3. Wait for deployment to complete"
echo "4. Clear browser cache (incognito mode or hard reload)"

